version: 2

models:
  - name: slv_orders

    columns:
      - name: order_id
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: sales
        tests:
          - not_null

      - name: quantity
        tests:
          - not_null